sudo: false
language: node_js
node_js:
  - 14
  - 16
  - 18
  - 20
  - 22
script:
  - yarn install --non-interactive
  - yarn lint
  - yarn coverage
notifications:
  email:
    on_success: never
    on_failure: always
