/* eslint-disable max-len */
const _ = require('lodash');
const toLowerCase = require('../utils/toLowerCase');
const { getLast, withoutLast } = require('../utils/listUtils');

const convertNow = now => [
  'on',
  {
    day: now.getDate(),
    groupType: 'date',
    month: now.getMonth() + 1,
    year: now.getFullYear(),
  },
];

const generateMap = () => [
  ..._.times(
    20, i => ({
      from: ['early', 'in', 'the', `${i + 4}th`, 'century'],
      to: ['in', 'the', 'early', `${i + 4}th`, 'century'],
    }),
  ),
];

const createDefaultMap = ({ now }) => [
  ...generateMap(),
  { from: ['&'], to: ['and'] },
  { from: [',', 'are'], to: ['are'] },
  { from: [',', 'colloquially', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'currently', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'either', 'directly', 'or', 'indirectly', ','], to: [] },
  { from: [',', 'excluding'], to: ['excluding'] },
  { from: [',', 'formerly', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'historically', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'in', 'fact', ','], to: [] },
  { from: [',', 'in', 'protest', 'against'], to: [',', 'due', 'to'] },
  { from: [',', 'in', 'protest', 'of'], to: [',', 'due', 'to'] },
  { from: [',', 'in', 'turn', ','], to: [] },
  { from: [',', 'including'], to: ['including'] },
  { from: [',', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'meanwhile', ','], to: [] },
  { from: [',', 'officially', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'on', 'the', 'other', 'hand', ','], to: [] },
  { from: [',', 'on', 'the', 'other', 'hand'], to: [] },
  { from: [',', 'originally', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'out', 'of', 'a', 'population', 'of'], to: ['out', 'of'] },
  { from: [',', 'popularly', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'previously', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'simply', 'known', 'as'], to: ['#alternative-name'] },
  { from: [',', 'sometimes', 'known', 'as'], to: ['#alternative-name'] },
  { from: ['1st'], to: ['first'] },
  { from: ['21st'], to: ['twenty-first'] },
  { from: ['2nd'], to: ['second'] },
  { from: ['3rd'], to: ['third'] },
  { from: ['a', 'dozen'], to: ['10'] },
  { from: ['a', 'few', 'hundred'], to: ['101–1000'] },
  { from: ['a', 'few'], to: ['several'] },
  { from: ['a', 'half', 'of', 'a', 'million'], to: ['5e5'] },
  { from: ['a', 'half', 'of', 'the'], to: ['50', '%', 'of', 'the'] },
  { from: ['a', 'half', 'the'], to: ['50', '%', 'of', 'the'] },
  { from: ['a', 'handful', 'of'], to: ['handful'] },
  { from: ['a', 'hundred'], to: ['100'] },
  { from: ['a', 'large', 'majority', 'of'], to: ['above', '60', '%', 'of'] },
  { from: ['a', 'large', 'part', 'of'], to: ['above', '20', '%', 'of'] },
  { from: ['a', 'little', 'more', 'than'], to: ['above'] },
  { from: ['a', 'long', 'time', 'ago'], to: ['over', '100', 'years', 'ago'] },
  { from: ['a', 'majority', 'of'], to: ['above', '50', '%', 'of'] },
  { from: ['a', 'number', 'of'], to: ['number'] },
  { from: ['a', 'quarter', 'of', 'a', 'million'], to: ['25e4'] },
  { from: ['a', 'quarter'], to: ['one', 'quarter'] },
  { from: ['a', 'third'], to: ['one', 'third'] },
  { from: ['a', 'thousand'], to: ['1000'] },
  { from: ['a', 'total', 'of'], to: [] },
  { from: ['a', 'variety', 'of'], to: ['many'] },
  { from: ['a', 'vast', 'majority', 'of'], to: ['above', '60', '%', 'of'] },
  { from: ['abundant', 'numbers', 'of'], to: ['many'] },
  { from: ['after', 'only'], to: ['after'] },
  { from: ['after', 'the', 'fall', 'of', 'the', 'roman', 'empire'], to: ['since', '476'] },
  { from: ['after', 'the', 'february', 'revolution', 'of', '1917'], to: ['since', '1917'] },
  { from: ['after', 'the', 'february', 'revolution'], to: ['since', '1917'] },
  { from: ['again', 'by'], to: ['by'] },
  { from: ['almost', 'all'], to: ['above', '90', '%', 'of'] },
  { from: ['although'], to: ['but'] },
  { from: ['american', 'dollars'], to: ['USDs'] },
  { from: ['an', 'estimated'], to: ['around'] },
  { from: ['an', 'increasing', 'number', 'of'], to: ['many'] },
  { from: ['an', 'overwhelming', 'majority', 'of'], to: ['above', '75', '%', 'of'] },
  { from: ['ancient', 'egyptian'], to: ['Egyptian', 'ancient'] },
  { from: ['and', 'are'], to: ['and', 'they', 'are'] },
  { from: ['and', 'had'], to: ['and', 'it', 'had'] },
  { from: ['and', 'has'], to: ['and', 'it', 'has'] },
  { from: ['and', 'is'], to: ['and', 'it', 'is'] },
  { from: ['and', 'was'], to: ['and', 'it', 'was'] },
  { from: ['and', 'were'], to: ['and', 'they', 'were'] },
  { from: ['annually'], to: ['every', '1', 'years'] },
  { from: ['appear', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['appears', 'to', 'have'], to: ['likely', 'has'] },
  { from: ['appears', 'to', 'show'], to: ['apparently', 'shows'] },
  { from: ['approximately', 'in'], to: ['in', 'approximately'] },
  { from: ['are', 'anticipated', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['are', 'believed', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['are', 'considered', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['are', 'inferred', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['are', 'judged', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['are', 'perceived', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['are', 'regarded', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['are', 'thought', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['area', 'that', 'is', 'now'], to: ['current', 'area', 'of'] },
  { from: ['as', 'a', 'general', 'rule'], to: ['generally'] },
  { from: ['as', 'early', 'as'], to: ['in'] },
  { from: ['as', 'high', 'as'], to: [] },
  { from: ['as', 'late', 'as', 'the'], to: ['in', 'the'] },
  { from: ['as', 'low', 'as'], to: [] },
  { from: ['as', 'many', 'as'], to: [] },
  { from: ['as', 'many', 'times', 'as', 'possible'], to: ['above', 'thrice'] },
  { from: ['as', 'much', 'as'], to: [] },
  { from: ['as', 'of'], to: ['in'] },
  { from: ['as', 'recently', 'as'], to: [] },
  { from: ['as', 'well', 'as'], to: ['and'] },
  { from: ['as', 'well'], to: [] },
  { from: ['at', 'least'], to: ['above'] },
  { from: ['at', 'the', 'beginning', 'of', 'the'], to: ['in', 'the', 'early'] },
  { from: ['at', 'the', 'end', 'of', 'the'], to: ['in', 'the', 'late'] },
  { from: ['at', 'the', 'same', 'time', 'at', 'the', 'same', 'time'], to: ['at', 'the', 'same', 'time', ','] },
  { from: ['at', 'the', 'same', 'time'], to: ['at', 'the', 'same', 'time', ','] },
  { from: ['at', 'the', 'time', 'of', 'the'], to: ['in', 'the'] },
  { from: ['at', 'times'], to: ['occasionally'] },
  { from: ['b.c.e'], to: ['BCE'] },
  { from: ['back', 'in', 'the'], to: ['in', 'the'] },
  { from: ['bc'], to: ['BCE'] },
  { from: ['because', 'of'], to: [',', 'due', 'to'] },
  { from: ['before'], to: ['by'] },
  { from: ['beginning', 'in', 'the', 'year'], to: ['since'] },
  { from: ['beginning', 'in'], to: ['since'] },
  { from: ['beginning', 'on'], to: ['since'] },
  { from: ['between', 'world', 'war', 'i', 'and', 'world', 'war', 'ii'], to: ['during', 'the', 'Interwar', 'Period'] },
  { from: ['biannually'], to: ['every', '6', 'months'] },
  { from: ['billions', 'of'], to: ['above', 'one', 'billion'] },
  { from: ['both', 'in'], to: ['in', 'both'] },
  { from: ['but'], to: [',', 'but'] },
  { from: ['by', 'contrast'], to: [] },
  { from: ['by', 'the', 'start', 'of'], to: ['#by-the-start-of'] },
  { from: ['c.'], to: ['around'] },
  { from: ['century', 'ce'], to: ['century'] },
  { from: ['colloquially', 'known', 'as'], to: ['known', 'as'] },
  { from: ['commencing', 'on'], to: ['since'] },
  { from: ['commonly', 'known', 'as'], to: ['known', 'as'] },
  { from: ['continues', 'to', 'be'], to: ['is'] },
  { from: ['countless', 'numbers', 'of'], to: ['many'] },
  { from: ['countries', 'such', 'as'], to: [] },
  { from: ['currently', 'known', 'as'], to: ['known', 'as'] },
  { from: ['currently'], to: convertNow(now) },
  { from: ['date', 'back', 'to'], to: ['started', 'in'] },
  { from: ['dates', 'back', 'to'], to: ['started', 'in'] },
  { from: ['dates', 'to', 'perhaps'], to: ['started', 'in', 'about'] },
  { from: ['dates', 'to'], to: ['started', 'in'] },
  { from: ['dating', 'back', 'to'], to: ['since'] },
  { from: ['did', 'not', 'have'], to: ['had', 'not'] },
  { from: ['dozens', 'of', 'billions', 'of'], to: ['above', '1e10'] },
  { from: ['dozens', 'of', 'millions', 'of'], to: ['above', '1e7'] },
  { from: ['dozens', 'of', 'thousands', 'of'], to: ['above', '1e4'] },
  { from: ['dozens', 'of', 'trillions', 'of'], to: ['above', '1e13'] },
  { from: ['dozens', 'of'], to: ['above', '10'] },
  { from: ['during', 'much', 'of', 'the'], to: ['in', 'the'] },
  { from: ['during', 'the', 'course', 'of', 'the'], to: ['in', 'the'] },
  { from: ['during', 'the', 'era', 'of', 'the', 'french', 'revolution'], to: ['during', 'the', 'French', 'Revolution'] },
  { from: ['during', 'the', 'final', 'stages', 'of', 'world', 'war', 'ii'], to: ['in', '1944–1945'] },
  { from: ['during', 'the', 'final', 'year', 'of', 'world', 'war', 'i'], to: ['in', '1918'] },
  { from: ['during', 'the', 'interwar', 'period'], to: ['during', 'the', 'Interwar', 'Period'] },
  { from: ['during', 'the', 'pleistocene', 'ice', 'age'], to: ['during', 'the', 'Pleistocene'] },
  { from: ['during', 'the', 'pleistocene', 'ice', 'ages'], to: ['during', 'the', 'Pleistocene'] },
  { from: ['during', 'the', 'revolutionary', 'war'], to: ['during', 'the', 'American', 'Revolutionary', 'War'] },
  { from: ['during', 'the'], to: ['in', 'the'] },
  { from: ['e.g.'], to: ['including'] },
  { from: ['early', 'to', 'mid'], to: ['early-to-mid'] },
  { from: ['eastern', 'half', 'of'], to: ['Eastern'] },
  { from: ['eastern'], to: ['Eastern'] },
  { from: ['enormous', 'numbers', 'of'], to: ['many'] },
  { from: ['estimated', 'at'], to: [] },
  { from: ['estimated', 'to', 'be'], to: [] },
  { from: ['estimated', 'to', 'have', 'been'], to: [] },
  { from: ['et', 'al.'], to: [',', 'and', 'others'] },
  { from: ['even', 'as', 'early', 'as', 'the'], to: ['in', 'the'] },
  { from: ['even', 'as', 'late', 'as', 'the'], to: ['in', 'the'] },
  { from: ['eventually', 'resulting', 'in'], to: ['resulting', 'in'] },
  { from: ['every', 'once', 'in', 'a', 'while'], to: ['occasionally'] },
  { from: ['every', 'other', 'day'], to: ['every', '2', 'days'] },
  { from: ['every', 'other', 'hour'], to: ['every', '2', 'hours'] },
  { from: ['every', 'other', 'month'], to: ['every', '2', 'months'] },
  { from: ['every', 'other', 'week'], to: ['every', '2', 'weeks'] },
  { from: ['every', 'other', 'year'], to: ['every', '2', 'years'] },
  { from: ['excluding', ':'], to: ['excluding'] },
  { from: ['few', 'or', 'no'], to: ['below', '100'] },
  { from: ['fewer', 'than'], to: ['below'] },
  { from: ['formally', 'recognised', 'as'], to: [] },
  { from: ['formerly', 'known', 'as'], to: ['known', 'as'] },
  { from: ['from', 'the', 'beginning', 'of'], to: ['since'] },
  { from: ['from', 'time', 'to', 'time'], to: ['occasionally'] },
  { from: ['generally', 'recognised', 'as'], to: [] },
  { from: ['had', 'been'], to: ['were'] },
  { from: ['half', 'of', 'the'], to: ['50', '%', 'of', 'the'] },
  { from: ['half', 'the'], to: ['50', '%', 'of', 'the'] },
  { from: ['has', 'been'], to: ['is'] },
  { from: ['has', 'had'], to: ['has'] },
  { from: ['has', 'often', 'been'], to: ['frequently', 'is'] },
  { from: ['have', 'been'], to: ['are'] },
  { from: ['historically', 'known', 'as'], to: ['known', 'as'] },
  { from: ['hundreds', 'of', 'billions', 'of'], to: ['above', '1e11'] },
  { from: ['hundreds', 'of', 'millions', 'of'], to: ['above', '1e8'] },
  { from: ['hundreds', 'of', 'thousands', 'of'], to: ['above', '1e5'] },
  { from: ['hundreds', 'of', 'trillions', 'of'], to: ['above', '1e14'] },
  { from: ['hundreds', 'of'], to: ['above', '100'] },
  { from: ['in', 'addition'], to: [] },
  { from: ['in', 'african', 'waters'], to: ['in', 'African', 'Waters'] },
  { from: ['in', 'american', 'waters'], to: ['in', 'American', 'Waters'] },
  { from: ['in', 'antarctic', 'waters'], to: ['in', 'Antarctic', 'Waters'] },
  { from: ['in', 'arctic', 'waters'], to: ['in', 'Arctic', 'Waters'] },
  { from: ['in', 'asian', 'waters'], to: ['in', 'Asian', 'Waters'] },
  { from: ['in', 'atlantic', 'waters'], to: ['in', 'Atlantic', 'Waters'] },
  { from: ['in', 'australian', 'waters'], to: ['in', 'Australian', 'Waters'] },
  { from: ['in', 'central', 'american', 'waters'], to: ['in', 'Central', 'American', 'Waters'] },
  { from: ['in', 'east', 'asian', 'waters'], to: ['in', 'East', 'Asian', 'Waters'] },
  { from: ['in', 'eurasia'], to: ['in', 'Asia', 'and', 'Europe'] },
  { from: ['in', 'european', 'waters'], to: ['in', 'European', 'Waters'] },
  { from: ['in', 'every'], to: ['every'] },
  { from: ['in', 'fact', ','], to: [] },
  { from: ['in', 'general'], to: ['generally'] },
  { from: ['in', 'indian', 'waters'], to: ['in', 'Indian', 'Waters'] },
  { from: ['in', 'mainland'], to: ['in', 'Mainland'] },
  { from: ['in', 'modern-day'], to: ['in'] },
  { from: ['in', 'north', 'american', 'waters'], to: ['in', 'North', 'American', 'Waters'] },
  { from: ['in', 'north', 'atlantic', 'waters'], to: ['in', 'North', 'Atlantic', 'Waters'] },
  { from: ['in', 'pacific', 'waters'], to: ['in', 'Pacific', 'Waters'] },
  { from: ['in', 'particular'], to: ['particularly'] },
  { from: ['in', 'reality'], to: [] },
  { from: ['in', 'south', 'american', 'waters'], to: ['in', 'South', 'American', 'Waters'] },
  { from: ['in', 'south', 'atlantic', 'waters'], to: ['in', 'South', 'Atlantic', 'Waters'] },
  { from: ['in', 'the', 'atlantic', 'and', 'indian', 'oceans'], to: ['in', 'Atlantic', 'Ocean', 'and', 'Indian', 'Ocean'] },
  { from: ['in', 'the', 'atlantic', 'and', 'pacific', 'oceans'], to: ['in', 'Atlantic', 'Ocean', 'and', 'Pacific', 'Ocean'] },
  { from: ['in', 'the', 'chicago', 'area'], to: ['in', 'the', 'Chicaco', 'Area'] },
  { from: ['in', 'the', 'earlier'], to: ['in', 'the', 'early'] },
  { from: ['in', 'the', 'east', 'of'], to: ['in', 'Eastern'] },
  { from: ['in', 'the', 'final', 'year', 'of', 'world', 'war', 'ii'], to: ['in', '1945'] },
  { from: ['in', 'the', 'hydra', 'constellation'], to: ['in', 'the', 'Hydra', 'Constellation'] },
  { from: ['in', 'the', 'indian', 'and', 'atlantic', 'oceans'], to: ['in', 'Indian', 'Ocean', 'and', 'Atlantic', 'Ocean'] },
  { from: ['in', 'the', 'indian', 'and', 'pacific', 'oceans'], to: ['in', 'Indian', 'Ocean', 'and', 'Pacific', 'Ocean'] },
  { from: ['in', 'the', 'later'], to: ['in', 'the', 'late'] },
  { from: ['in', 'the', 'mainland'], to: ['in', 'the', 'Mainland'] },
  { from: ['in', 'the', 'milky', 'way', 'galaxy'], to: ['in', 'the', 'Milky', 'Way'] },
  { from: ['in', 'the', 'north', 'of'], to: ['in', 'Northern'] },
  { from: ['in', 'the', 'northern', 'celestial', 'hemisphere'], to: ['in', 'the', 'Northern', 'Celestial', 'Hemisphere'] },
  { from: ['in', 'the', 'northern', 'sky'], to: ['in', 'the', 'Northern', 'Celestial', 'Hemisphere'] },
  { from: ['in', 'the', 'pacific', 'and', 'atlantic', 'oceans'], to: ['in', 'Pacific', 'Ocean', 'and', 'Atlantic', 'Ocean'] },
  { from: ['in', 'the', 'pacific', 'and', 'indian', 'oceans'], to: ['in', 'Pacific', 'Ocean', 'and', 'Indian', 'Ocean'] },
  { from: ['in', 'the', 'past', '12', 'months'], to: ['below', '1', 'years', 'ago'] },
  { from: ['in', 'the', 'south', 'of'], to: ['in', 'Southern'] },
  { from: ['in', 'the', 'southern', 'celestial', 'hemisphere'], to: ['in', 'the', 'Southern', 'Celestial', 'Hemisphere'] },
  { from: ['in', 'the', 'southern', 'sky'], to: ['in', 'the', 'Southern', 'Celestial', 'Hemisphere'] },
  { from: ['in', 'the', 'united', 'states', 'each', 'state'], to: ['in', 'the', 'United', 'States', ',', 'each', 'state'] },
  { from: ['in', 'the', 'united', 'states', 'of', 'america'], to: ['in', 'the', 'United', 'States'] },
  { from: ['in', 'the', 'ursa', 'major', 'constellation'], to: ['in', 'the', 'Ursa', 'Major', 'Constellation'] },
  { from: ['in', 'the', 'virgo', 'constellation'], to: ['in', 'the', 'Virgo', 'Constellation'] },
  { from: ['in', 'the', 'west', 'of'], to: ['in', 'Western'] },
  { from: ['in', 'the', 'world'], to: ['in', 'the', 'World'] },
  { from: ['in', 'total', ',', 'there', 'are'], to: ['there', 'are'] },
  { from: ['in', 'total', 'there', 'are'], to: ['there', 'are'] },
  { from: ['include', '(', 'but', 'not', 'limited', 'to', ')'], to: ['include', 'the'] },
  { from: ['include', ',', 'but', 'are', 'not', 'limited', 'to', ','], to: ['include', 'the'] },
  { from: ['include', 'but', 'are', 'by', 'no', 'means', 'limited', 'to'], to: ['include', 'the'] },
  { from: ['include', 'but', 'are', 'not', 'limited', 'to'], to: ['include', 'the'] },
  { from: ['include', 'but', 'are', 'not', 'restricted', 'to'], to: ['include', 'the'] },
  { from: ['include', 'but', 'not', 'limited', 'to'], to: ['include', 'the'] },
  { from: ['including', ':'], to: ['including'] },
  { from: ['internationally', 'recognised', 'as'], to: [] },
  { from: ['into', 'the'], to: ['until', 'the'] },
  { from: ['is', 'able', 'to', 'hold'], to: ['holds'] },
  { from: ['is', 'believed', 'to', 'be'], to: ['likely', 'is'] },
  { from: ['is', 'known', 'to', 'have', 'been'], to: ['was'] },
  { from: ['is', 'known', 'to', 'have'], to: ['have'] },
  { from: ['is', 'perceived', 'to', 'have'], to: ['likely', 'has'] },
  { from: ['is', 'proven', 'to', 'have'], to: ['has'] },
  { from: ['is', 'said', 'to', 'have'], to: ['likely', 'has'] },
  { from: ['is', 'thought', 'to', 'have'], to: ['likely', 'has'] },
  { from: ['it', 'has', 'been', 'suggested', 'that'], to: ['likely'] },
  { from: ['it', 'is', 'ambiguous', 'if'], to: ['perhaps'] },
  { from: ['it', 'is', 'believed', 'that'], to: ['likely'] },
  { from: ['it', 'is', 'known', 'that'], to: [] },
  { from: ['it', 'is', 'likely', 'that'], to: ['likely'] },
  { from: ['it', 'is', 'questionable', 'if'], to: ['perhaps'] },
  { from: ['it', 'is', 'said', 'that'], to: ['likely'] },
  { from: ['it', 'is', 'speculated', 'that'], to: ['likely'] },
  { from: ['it', 'is', 'thought', 'that'], to: ['likely'] },
  { from: ['it', 'is', 'uncertain', 'if'], to: ['perhaps'] },
  { from: ['it', 'is', 'undetermined', 'if'], to: ['perhaps'] },
  { from: ['it', 'is', 'unsure', 'if'], to: ['perhaps'] },
  { from: ['just', 'above'], to: ['above'] },
  { from: ['just', 'under'], to: ['below'] },
  { from: ['large', 'numbers', 'of'], to: ['many'] },
  { from: ['legally', 'recognised', 'as'], to: [] },
  { from: ['little', 'more', 'than'], to: ['above'] },
  { from: ['located', 'in', 'the', 'north', 'of', 'the', 'state', 'of'], to: ['in', 'the', 'Northern'] },
  { from: ['located', 'in', 'the', 'south', 'of', 'the', 'state', 'of'], to: ['in', 'the', 'Southern'] },
  { from: ['lost', 'their', 'lives'], to: ['lost', 'the', 'life'] },
  { from: ['majority', 'of'], to: ['above', '50', '%', 'of'] },
  { from: ['many', 'billions', 'of'], to: ['above', 'one', 'billion'] },
  { from: ['many', 'dozens', 'of'], to: ['above', '10'] },
  { from: ['many', 'hundreds', 'of', 'millions', 'of'], to: ['above', '1e8'] },
  { from: ['many', 'hundreds', 'of', 'thousands', 'of'], to: ['above', '1e5'] },
  { from: ['many', 'millions', 'of'], to: ['above', 'one', 'million'] },
  { from: ['many', 'of', 'the'], to: ['many'] },
  { from: ['many', 'thousands', 'of'], to: ['above', '1000'] },
  { from: ['many', 'trillions', 'of'], to: ['above', 'one', 'trillion'] },
  { from: ['may', 'be'], to: ['likely', 'is'] },
  { from: ['may', 'have', 'been'], to: ['likely', 'is'] },
  { from: ['may', 'have'], to: ['likely', 'has'] },
  { from: ['meanwhile', ','], to: [] },
  { from: ['mid', 'to', 'late'], to: ['mid-to-late'] },
  { from: ['middle', 'of', 'the'], to: ['mid'] },
  { from: ['million', 'years', 'ago', '(', 'mya', ')'], to: ['million', 'years', 'ago'] },
  { from: ['millions', 'of'], to: ['above', 'one', 'million'] },
  { from: ['modern', 'times'], to: [`${now.getFullYear() - 200}–${now.getFullYear()}`] },
  { from: ['more', 'recent', 'times'], to: [`${now.getFullYear() - 15}–${now.getFullYear()}`] },
  { from: ['more', 'recently'], to: ['in', `${now.getFullYear() - 5}–${now.getFullYear()}`] },
  { from: ['more', 'than'], to: ['above'] },
  { from: ['most', 'commonly', 'known', 'as'], to: ['known', 'as'] },
  { from: ['most', 'of'], to: ['above', '50', '%', 'of'] },
  { from: ['most', 'recently'], to: ['in', `${now.getFullYear() - 5}–${now.getFullYear()}`] },
  { from: ['much', 'more', 'than'], to: ['above'] },
  { from: ['much', 'of'], to: ['above', '20', '%', 'of'] },
  { from: ['multiple'], to: ['several'] },
  { from: ['nearly', 'all'], to: ['above', '90', '%', 'of'] },
  { from: ['no', 'more', 'than'], to: ['almost'] },
  { from: ['northeast'], to: ['Northeast'] },
  { from: ['northern', 'half', 'of'], to: ['Northern'] },
  { from: ['northern'], to: ['Northern'] },
  { from: ['northwest'], to: ['Northwest'] },
  { from: ['not', 'a', 'long', 'time', 'ago'], to: ['below', '100', 'years', 'ago'] },
  { from: ['not', 'excluding'], to: ['including'] },
  { from: ['not', 'including'], to: ['excluding'] },
  { from: ['now'], to: convertNow(now) },
  { from: ['nowadays'], to: convertNow(now) },
  { from: ['of', 'the', 'text'], to: ['of', 'the', 'texts'] },
  { from: ['officially', 'known', 'as'], to: ['known', 'as'] },
  { from: ['officially', 'recognised', 'as'], to: [] },
  { from: ['often', ',', 'but', 'not', 'always', ','], to: ['usually'] },
  { from: ['often', 'used'], to: ['used', 'frequently'] },
  { from: ['on', 'average'], to: ['typically'] },
  { from: ['on', 'every', 'continent', 'except', 'antarctica'], to: ['in', 'Africa', ',', 'America', ',', 'Asia', ',', 'Australia', 'and', 'Europe'] },
  { from: ['on', 'that', 'date', ','], to: ['at', 'the', 'same', 'time', ','] },
  { from: ['on', 'the', 'asian', 'mainland'], to: ['in', 'the', 'Asian', 'Mainland'] },
  { from: ['on', 'the', 'islands', 'of'], to: ['in'] },
  { from: ['on', 'the', 'japanese', 'city', 'of', 'hiroshima'], to: ['in', 'Hiroshima', ',', 'Japan'] },
  { from: ['on', 'the', 'japanese', 'city', 'of', 'nagasaki'], to: ['in', 'Nagasaki', ',', 'Japan'] },
  { from: ['on', 'the', 'japanese', 'islands', 'of'], to: ['in'] },
  { from: ['on', 'the', 'night', 'of'], to: ['on'] },
  { from: ['on', 'the', 'other', 'hand', ','], to: [] },
  { from: ['on', 'the', 'other', 'hand'], to: [] },
  { from: ['once', 'in', 'a', 'while'], to: ['occasionally'] },
  { from: ['once'], to: ['1', 'times'] },
  { from: ['one', 'half', 'of', 'the'], to: ['50', '%', 'of', 'the'] },
  { from: ['one', 'half', 'the'], to: ['50', '%', 'of', 'the'] },
  { from: ['one-fifth'], to: ['20', '%'] },
  { from: ['one-fourth'], to: ['25', '%'] },
  { from: ['one-third'], to: ['one', 'third'] },
  { from: ['or', 'simply'], to: ['or'] },
  { from: ['originally', 'known', 'as'], to: ['known', 'as'] },
  { from: ['out', 'of', 'a', 'population', 'of'], to: ['out', 'of'] },
  { from: ['over', 'the', 'course', 'of', 'many', 'centuries'], to: ['above', '300', 'years', 'ago'] },
  { from: ['over', 'the', 'course', 'of', 'many', 'generations'], to: ['above', '100', 'years', 'ago'] },
  { from: ['over', 'the', 'course', 'of', 'many', 'years'], to: ['above', '5', 'years', 'ago'] },
  { from: ['over', 'the', 'course', 'of', 'the'], to: ['in', 'the'] },
  { from: ['over', 'the', 'last', 'couple', 'of'], to: ['over', 'the', 'last', 'several'] },
  { from: ['over', 'the', 'last', 'decade'], to: ['over', 'the', 'last', '10', 'years'] },
  { from: ['over', 'the', 'last', 'few'], to: ['over', 'the', 'last', 'several'] },
  { from: ['over', 'the', 'last', 'half', 'a', 'century'], to: ['over', 'the', 'last', '50', 'years'] },
  { from: ['over', 'the', 'years'], to: ['above', '3', 'years', 'ago'] },
  { from: ['perhaps'], to: ['likely'] },
  { from: ['popularly', 'known', 'as'], to: ['known', 'as'] },
  { from: ['pretend', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['pretends', 'to', 'have'], to: ['likely', 'has'] },
  { from: ['previously', 'known', 'as'], to: ['known', 'as'] },
  { from: ['prior', 'to'], to: ['before'] },
  { from: ['quite', 'a', 'long', 'time', 'ago'], to: ['over', '200', 'years', 'ago'] },
  { from: ['recent', 'centuries'], to: [`${now.getFullYear() - 400}–${now.getFullYear()}`] },
  { from: ['recent', 'decades'], to: [`${now.getFullYear() - 40}–${now.getFullYear()}`] },
  { from: ['recent', 'times'], to: [`${now.getFullYear() - 20}–${now.getFullYear()}`] },
  { from: ['recent', 'years'], to: [`${now.getFullYear() - 15}–${now.getFullYear()}`] },
  { from: ['second', 'largest'], to: ['second-largest'] },
  { from: ['second', 'world', 'war'], to: ['World', 'War', 'II'] },
  { from: ['seem', 'to', 'have'], to: ['likely', 'have'] },
  { from: ['seems', 'to', 'have'], to: ['likely', 'has'] },
  { from: ['several', 'hundred'], to: ['101–1000'] },
  { from: ['several', 'times', 'a', 'day'], to: ['every', '2–8', 'hours'] },
  { from: ['several', 'times', 'a', 'minute'], to: ['every', '6–20', 'seconds'] },
  { from: ['several', 'times', 'a', 'month'], to: ['every', '3–10', 'days'] },
  { from: ['several', 'times', 'a', 'week'], to: ['every', '1–3', 'days'] },
  { from: ['several', 'times', 'a', 'year'], to: ['every', '36–122', 'days'] },
  { from: ['several', 'times', 'an', 'hour'], to: ['every', '6–20', 'minutes'] },
  { from: ['significant', 'numbers', 'of'], to: ['many'] },
  { from: ['simply', 'known', 'as'], to: ['known', 'as'] },
  { from: ['since', 'about', 'the'], to: ['since', 'the'] },
  { from: ['since', 'after'], to: ['since'] },
  { from: ['since', 'approximately', 'the'], to: ['since', 'the'] },
  { from: ['since', 'around', 'the'], to: ['since', 'the'] },
  { from: ['since', 'before'], to: ['since'] },
  { from: ['since', 'roughly', 'the'], to: ['since', 'the'] },
  { from: ['so', 'many'], to: ['many'] },
  { from: ['sometimes', 'known', 'as'], to: ['known', 'as'] },
  { from: ['southeast'], to: ['Southeast'] },
  { from: ['southern', 'half', 'of'], to: ['Southern'] },
  { from: ['southern'], to: ['Southern'] },
  { from: ['southwest'], to: ['Southwest'] },
  { from: ['starting', 'from'], to: ['since'] },
  { from: ['starting', 'in'], to: ['since'] },
  { from: ['starting'], to: ['since'] },
  { from: ['strictly', 'speaking'], to: [] },
  { from: ['such', 'as'], to: [':'] },
  { from: ['synonymous', 'with'], to: ['known', 'as'] },
  { from: ['taken', 'prisoner'], to: ['imprisoned'] },
  { from: ['tens', 'of', 'thousands', 'of'], to: ['above', '1e4'] },
  { from: ['the', 'city', 'of'], to: [] },
  { from: ['the', 'expectation', 'is', 'that'], to: ['likely'] },
  { from: ['the', 'following', 'year'], to: ['1', 'years', 'later'] },
  { from: ['the', 'great', 'depression', 'of', 'the', '1930s'], to: ['the', 'Great', 'Depression'] },
  { from: ['the', 'great', 'majority', 'of'], to: ['above', '60', '%', 'of'] },
  { from: ['the', 'handful', 'of'], to: ['handful'] },
  { from: ['the', 'large', 'majority', 'of'], to: ['above', '60', '%', 'of'] },
  { from: ['the', 'latter', 'half', 'of', 'the'], to: ['the', 'late'] },
  { from: ['the', 'majority', 'of'], to: ['above', '50', '%', 'of'] },
  { from: ['the', 'next', 'year'], to: ['1', 'years', 'later'] },
  { from: ['the', 'number', 'of'], to: ['the', 'amount', 'of'] },
  { from: ['the', 'overwhelming', 'majority', 'of'], to: ['above', '75', '%', 'of'] },
  { from: ['the', 'preceding', 'year'], to: ['1', 'years', 'earlier'] },
  { from: ['the', 'previous', 'year'], to: ['1', 'years', 'earlier'] },
  { from: ['the', 'second', 'half', 'of', 'the'], to: ['the', 'late'] },
  { from: ['the', 'vast', 'majority', 'of'], to: ['above', '60', '%', 'of'] },
  { from: ['the', 'whole', 'of'], to: ['the', 'Whole'] },
  { from: ['then', 'the', 'following', 'year'], to: ['1', 'years', 'later'] },
  { from: ['then', 'the', 'next', 'year'], to: ['1', 'years', 'later'] },
  { from: ['there', 'could', 'be'], to: ['there', 'are', 'likely'] },
  { from: ['third', 'largest'], to: ['third-largest'] },
  { from: ['though'], to: ['but'] },
  { from: ['thousands', 'of'], to: ['above', '1000'] },
  { from: ['thrice', 'a', 'year'], to: ['every', '4', 'months'] },
  { from: ['thrice'], to: ['3', 'times'] },
  { from: ['through', 'centuries'], to: ['over', '300', 'years', 'ago'] },
  { from: ['throughout'], to: ['in'] },
  { from: ['thus', 'resulting', 'in'], to: ['resulting', 'in'] },
  { from: ['today'], to: convertNow(now) },
  { from: ['triannually'], to: ['every', '4', 'months'] },
  { from: ['trillions', 'of'], to: ['above', 'one', 'trillion'] },
  { from: ['twice', 'a', 'year'], to: ['every', '6', 'months'] },
  { from: ['twice'], to: ['2', 'times'] },
  { from: ['two-thirds'], to: ['two', 'thirds'] },
  { from: ['u.s.', 'dollars'], to: ['USDs'] },
  { from: ['ultimately', 'resulting', 'in'], to: ['resulting', 'in'] },
  { from: ['united', 'states', 'dollars'], to: ['USDs'] },
  { from: ['universally', 'recognised', 'as'], to: [] },
  { from: ['until', 'about', 'the'], to: ['until', 'the'] },
  { from: ['until', 'approximately', 'the'], to: ['until', 'the'] },
  { from: ['until', 'around', 'the'], to: ['until', 'the'] },
  { from: ['until', 'roughly', 'the'], to: ['until', 'the'] },
  { from: ['until'], to: ['by'] },
  { from: ['up', 'to'], to: ['below'] },
  { from: ['us', 'dollars'], to: ['USDs'] },
  { from: ['usually', 'synonymous', 'with'], to: ['known', 'as'] },
  { from: ['vast', 'numbers', 'of'], to: ['many'] },
  { from: ['was', 'in', 'fact', 'a'], to: ['was', 'a'] },
  { from: ['was', 'in', 'fact', 'an'], to: ['was', 'an'] },
  { from: ['was', 'supposed', 'to', 'have'], to: ['likely', 'has'] },
  { from: ['well', 'over'], to: ['above'] },
  { from: ['western', 'half', 'of'], to: ['Western'] },
  { from: ['western'], to: ['Western'] },
  { from: ['what', 'is', 'now'], to: [] },
  { from: ['which'], to: [',', 'which'] },
  { from: ['whole', 'hundreds', 'of'], to: ['above', '100'] },
  { from: ['widely', 'recognised', 'as'], to: [] },
  { from: ['world', 'war', 'i'], to: ['the', 'World', 'War', 'I'] },
  { from: ['world', 'war', 'ii'], to: ['the', 'World', 'War', 'II'] },
  { from: ['worldwide'], to: ['in', 'the', 'World'] },
];

const convertSynonyms = ({ now, createMap = createDefaultMap } = {}) => (phrase) => {
  const maps = _.sortBy(
    Object.entries(
      _.groupBy(createMap({ now }), x => x.from.length),
    ),
    ([key]) => -Number(key),
  )
    .map(([, value]) => value);

  const converters = maps.map(map => currentPhrase => currentPhrase.reduce((accumulator, current) => {
    const found = map.find(e => JSON.stringify(
      getLast(
        [...accumulator, current].map(toLowerCase),
        e.from.length,
      ),
    ) === JSON.stringify(e.from));
    if (found) {
      return [
        ...withoutLast(accumulator, found.from.length - 1),
        ...found.to,
      ];
    }

    return [
      ...accumulator,
      current,
    ];
  },
  []));

  return _.flow(converters)(phrase);
};

module.exports = convertSynonyms;
